package org.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataMonitoring implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "enddate")
   private java.util.Date enddate;
   @org.kie.api.definition.type.Label(value = "startdate")
   private java.util.Date startdate;

   public DataMonitoring()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.Date getEnddate()
   {
      return this.enddate;
   }

   public void setEnddate(java.util.Date enddate)
   {
      this.enddate = enddate;
   }

   public java.util.Date getStartdate()
   {
      return this.startdate;
   }

   public void setStartdate(java.util.Date startdate)
   {
      this.startdate = startdate;
   }

   public DataMonitoring(java.lang.String name, java.util.Date enddate,
         java.util.Date startdate)
   {
      this.name = name;
      this.enddate = enddate;
      this.startdate = startdate;
   }

}